[package]
name = "sqlmo_sqlx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22.0", features = ["full"], optional = true }
sqlmo = { path = ".." }
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres"] }
anyhow = "1.0.66"
itertools = "0.10.5"
async-trait = "0.1.71"
